### PR TITLE
chore(poetry): pin pydantic to v1

### PR DESCRIPTION
**Pull request by catcombo**
Pin Pydantic to V1 until we're ready to work on the upgrade. Otherwise, it causes problems when installing the `youtrack-sdk` because `poetry` tries to use the latest Pydantic.

### CODE REVIEW

**Comment by zyv** [comment]
I don't think this is a good idea. Pydantic V2 includes a complete copy of V1. I would just switch imports.

**Comment by catcombo** [comment]
> I don't think this is a good idea. Pydantic V2 includes a complete copy of V1. I would just switch imports.

I replaced imports to backport but it doesn't help. It blocks us from bumping dependencies in other projects. Or bump all dependencies manually except `youtrack-sdk`.

**Comment by zyv** [comment]
> > I don't think this is a good idea. Pydantic V2 includes a complete copy of V1. I would just switch imports.
> 
> I replaced imports to backport but it doesn't help. It blocks us from bumping dependencies in other projects. Or bump all dependencies manually except `youtrack-sdk`.

So what exactly is the problem? It is supposed to work:

https://github.com/pydantic/pydantic#pydantic-v110-vs-v2

If it doesn't, we should report a bug. I can't try to reproduce it myself right now.

**Comment by catcombo** [comment]
The bug is already reported https://github.com/pydantic/pydantic/issues/6361 They plan to deploy a new release today.

**Comment by catcombo** [comment]
Pydantic developers released a version 2.0.1 that includes bug fixes. Now we can upgrade dependencies to Pydantic V2 and use V1 from a copy.

**Review by zyv — APPROVED** [review]

**Pull request merged**
